//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp26
{
    using System;
    using System.Collections.Generic;
    
    public partial class orders
    {
        public int id { get; set; }
        public string articul { get; set; }
        public Nullable<System.DateTime> date_order { get; set; }
        public Nullable<System.DateTime> date_delivery { get; set; }
        public int pvz_id { get; set; }
        public string client { get; set; }
        public Nullable<int> code { get; set; }
        public string status { get; set; }
    
        public virtual pvz pvz { get; set; }
    }
}
