//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoApp26
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public int id { get; set; }
        public string articul { get; set; }
        public string name { get; set; }
        public string edizm { get; set; }
        public int price { get; set; }
        public string supplier { get; set; }
        public string manufacturer { get; set; }
        public string category { get; set; }
        public Nullable<int> sale { get; set; }
        public int count { get; set; }
        public string description { get; set; }
        public string photo_url { get; set; }
    }
}
